if we do exception handling in loop. if an exception is thown loop will not terminate 
for{
try{}catch{}
}